// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseACPSession(arg1:string):Promise<string>;

export function ConnectACP():Promise<string>;

export function ConnectAgent(arg1:string):Promise<string>;

export function CreateACPSession(arg1:string):Promise<string>;

export function DisconnectACP():Promise<string>;

export function DisconnectAgent(arg1:string):Promise<string>;

export function GetACPStatus():Promise<Record<string, any>>;

export function GetAgentInfo(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InitACP(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ListConnectedAgents():Promise<string>;

export function SendACPMessage(arg1:string,arg2:string):Promise<string>;
