// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseACPSession(arg1) {
  return window['go']['services']['App']['CloseACPSession'](arg1);
}

export function ConnectACP() {
  return window['go']['services']['App']['ConnectACP']();
}

export function ConnectAgent(arg1) {
  return window['go']['services']['App']['ConnectAgent'](arg1);
}

export function CreateACPSession(arg1) {
  return window['go']['services']['App']['CreateACPSession'](arg1);
}

export function DisconnectACP() {
  return window['go']['services']['App']['DisconnectACP']();
}

export function DisconnectAgent(arg1) {
  return window['go']['services']['App']['DisconnectAgent'](arg1);
}

export function GetACPStatus() {
  return window['go']['services']['App']['GetACPStatus']();
}

export function GetAgentInfo(arg1) {
  return window['go']['services']['App']['GetAgentInfo'](arg1);
}

export function Greet(arg1) {
  return window['go']['services']['App']['Greet'](arg1);
}

export function InitACP(arg1, arg2, arg3) {
  return window['go']['services']['App']['InitACP'](arg1, arg2, arg3);
}

export function ListConnectedAgents() {
  return window['go']['services']['App']['ListConnectedAgents']();
}

export function SendACPMessage(arg1, arg2) {
  return window['go']['services']['App']['SendACPMessage'](arg1, arg2);
}
