// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['services']['App']['CloseWindow']();
}

export function Greet(arg1) {
  return window['go']['services']['App']['Greet'](arg1);
}

export function MinimizeWindow() {
  return window['go']['services']['App']['MinimizeWindow']();
}
